matrix:
  include:
    - language: java
      before_script:
        - chmod a+x mvnw
      script:
        - ./mvnw clean package

    - language: node_js
      node_js:
        - "6.11"
      before_script:
        - yarn install
      script:
        - yarn build