matrix:
  include:
    - language: java
      before_install:
        - chmod +x mvnw
      script:
        - ./mvnw compile
        - ./mvnw -Pspotbugs spotbugs:check

    - language: node_js
      node_js:
        - "6.11"
      install:
        - yarn install
      script:
        - yarn build
