matrix:
  include:
    - language: java
      script:
        - mvn compile

    - language: node_js
      node_js:
        - "6.11"
      before_script:
        - yarn install
      script:
        - yarn build