matrix:
  include:
    - language: java
      script:
        - ./mvnw clean package

    - language: node_js
      node_js:
        - "7"
      before_script:
        - yarn install
      script:
        - yarn build